//
//  languageNew.h
//  shinelink
//
//  Created by sky on 16/5/3.
//  Copyright © 2016年 sky. All rights reserved.
//

#ifndef languageNew_h
#define languageNew_h



#pragma mark - 登陆
#define  root_liji_tiyan       NSLocalizedString(@"立即体验", nil)
#define  root_next_go        NSLocalizedString(@"下一步", nil)
#define  root_finish        NSLocalizedString(@"完成", nil)
#define  root_server_error        NSLocalizedString(@"服务器错误", nil)
#define  root_paiZhao        NSLocalizedString(@"拍照", nil)
#define  root_xiangkuang_xuanQu        NSLocalizedString(@"从相册选取", nil)
#define  root_cancel        NSLocalizedString(@"取消", nil)
#define  root_ALET        NSLocalizedString(@"警告", nil)
#define  root_OK        NSLocalizedString(@"确定", nil)
#define  root_del        NSLocalizedString(@"删除", nil)
#define  root_saomiao_jieguo       NSLocalizedString(@"扫描结果", nil)
#define  root_set       NSLocalizedString(@"配置", nil)


//登陆
#define root_Enter_your_username       NSLocalizedString(@"Enter your username", @"Enter your username")
#define root_Enter_your_pwd       NSLocalizedString(@"Enter your pwd", @"Enter your pwd")
#define root_forget_pwd       NSLocalizedString(@"忘记密码", nil)
#define root_register       NSLocalizedString(@"注册", nil)
#define root_log_in      NSLocalizedString(@"登陆", nil)
#define root_demo_test      NSLocalizedString(@"体验馆", nil)
#define  root_Alet_user        NSLocalizedString(@"温馨提示 ", nil)
#define  root_Alet_user_messge        NSLocalizedString(@"请输入用户名 ", nil)
#define  root_Alet_user_pwd        NSLocalizedString(@"请输入密码 ", nil)

#define  root_demo_Alert        NSLocalizedString(@"浏览用户禁止操作", nil)
#define  root_huoqu_wufuqi_dizhi        NSLocalizedString(@"获取服务器地址", nil)

//注册

#define  root_country        NSLocalizedString(@"国家", nil)
#define  root_country_alet        NSLocalizedString(@"点击选择国家", nil)
#define  root_country_kong        NSLocalizedString(@"请选择国家和城市", nil)
#define  root_country_huoQu        NSLocalizedString(@"请再次进入页面获取国家列表", nil)

#define  root_yongHuMing        NSLocalizedString(@"用户名", nil)
#define  root_Mima        NSLocalizedString(@"密码", nil)
#define  root_chongFu_miMa        NSLocalizedString(@"重复密码", nil)
#define  root_chongFu_shuRu_miMa       NSLocalizedString(@"重复输入密码", nil)
#define  root_dianzZiYouJian        NSLocalizedString(@"电子邮箱", nil)
#define  root_DianHua        NSLocalizedString(@"联系电话", nil)
#define  root_daiLiShangBianHao        NSLocalizedString(@"代理商编号", nil)
#define  root_shuRu_daiLiShangBianHao        NSLocalizedString(@"输入代理商编号", nil)
#define  root_xiangTong_miMa        NSLocalizedString(@"请输入相同的密码", nil)
#define  root_daYu_san       NSLocalizedString(@"用户名必须大于3位", nil)
#define  root_daYu_liu        NSLocalizedString(@"密码必须大于6位", nil)
#define  root_weiZhi       NSLocalizedString(@"位置", nil)
#define  root_weiZhi_tiShi        NSLocalizedString(@"点击获取城市和经纬度", nil)
#define root_Enter_email       NSLocalizedString(@"Enter email", @"Enter email")
#define root_Enter_phone_number       NSLocalizedString(@"Enter phone number", @"Enter phone number")
#define root_Networking      NSLocalizedString(@"Networking Timeout", @"Networking Timeout")
#define root_Yes       NSLocalizedString(@"Yes", @"Yes")
#define  root_caiJiQi         NSLocalizedString(@"请输入采集器序列号", nil)
#define  root_caiJiQi_zhengque        NSLocalizedString(@"请输入正确采集器序列号", nil)
#define  root_jiaoYanMa       NSLocalizedString(@"请输入采集器校验码", nil)
#define  root_jiaoYanMa_zhengQue       NSLocalizedString(@"请输入正确采集器校验码", nil)
#define  root_erWeiMa       NSLocalizedString(@"扫描条形码", nil)
#define  root_weiZhi       NSLocalizedString(@"位置", nil)

#define  root_chaoChu_shuLiang       NSLocalizedString(@"超出版本限制注册用户数量", nil)
#define  root_fuWuQi_cuoWu      NSLocalizedString(@"服务器错误", nil)
#define  root_zhuCe_cuoWu       NSLocalizedString(@"注册错误", nil)
#define  root_caijiqi_cuowu       NSLocalizedString(@"采集器序列号或校验码错误", nil)
#define  root_dailishang_cuowu       NSLocalizedString(@"代理商编码错误", nil)
#define  root_zhuCe_chengGong      NSLocalizedString(@"注册成功", nil)
#define  root_yongHu_yi_shiYong       NSLocalizedString(@"用户名已被使用", nil)

#define  root_zhaohui_mima      NSLocalizedString(@"找回密码", nil)
#define  root_tongGuo_yonghuMing       NSLocalizedString(@"通过用户名", nil)
#define  root_tongGuo_xuLieHao       NSLocalizedString(@"通过序列号", nil)
#define  root_zhengQueDe_yonghuMing       NSLocalizedString(@"请输入正确的用户名", nil)
#define  root_youJian_shiBai       NSLocalizedString(@"发送邮件失败", nil)
#define  root_zhaoBuDao_yongHu       NSLocalizedString(@"不能找到用户名", nil)
#define  root_peiZhi_sheBei      NSLocalizedString(@"配置设备", nil)
#define  root_jiaoYanMa_cuoWu      NSLocalizedString(@"校验码错误", nil)


#pragma mark - 设备
//设备
#define  root_device        NSLocalizedString(@"设备", nil)
#define  root_shiFan_dianZhan        NSLocalizedString(@"示范电站", nil)
#define  root_niBianQi        NSLocalizedString(@"逆变器", nil)
#define  root_chuNengJi        NSLocalizedString(@"储能机", nil)
#define  root_chongDianZhuang        NSLocalizedString(@"充电桩", nil)
#define  root_gongLvTiaoJieQi       NSLocalizedString(@"功率调节器", nil)
#define  root_wei_LianJie       NSLocalizedString(@"未连接", nil)
#define  root_tianJia_sheBei       NSLocalizedString(@"添加设备", nil)
#define  root_xiTong_CuoWu      NSLocalizedString(@"系统错误", nil)
#define  root_shanChu_chengGong      NSLocalizedString(@"删除成功", nil)
#define root_caiJiQi_leiBiao  NSLocalizedString(@"采集器列表", nil)

#define root_Add_Plant       NSLocalizedString(@"Add Plant", @"Add Plant")
#define root_Remove_Station       NSLocalizedString(@"Remove Station", @"Remove Station")
#define root_Upload_Picture       NSLocalizedString(@"Upload Picture", @"Upload Picture")
#define root_Cancel       NSLocalizedString(@"Cancel", @"Cancel")

#define root_xitong_cuoWu       NSLocalizedString(@"系统错误", nil)
#define root_xiuGai_chengGong       NSLocalizedString(@"修改成功", nil)
#define root_yi_peiZhi       NSLocalizedString(@"已配置设备", nil)
#define root_wei_peiZhi       NSLocalizedString(@"未配置设备", nil)
#define root_ri_dianLiang       NSLocalizedString(@"日电量:", nil)
#define root_dianChi_baifenBi       NSLocalizedString(@"电池百分比:", nil)
#define root_bianJi       NSLocalizedString(@"编辑", nil)
#define root_zhiDing       NSLocalizedString(@"置顶 ", nil)

#define root_dengDai       NSLocalizedString(@"等待 ", nil)
#define root_zhengChang       NSLocalizedString(@"正常 ", nil)
#define root_cuoWu      NSLocalizedString(@"故障", nil)
#define root_duanKai       NSLocalizedString(@"断开", nil)
#define root_xianZhi       NSLocalizedString(@"闲置 ", nil)
#define root_chongDian       NSLocalizedString(@"充电 ", nil)
#define root_fangDian       NSLocalizedString(@"放电 ", nil)
#define root_xianQing       NSLocalizedString(@"详情 ", nil)
#define root_gongLv       NSLocalizedString(@"功率:", nil)

#define root_bieMing       NSLocalizedString(@"请输入设备别名", nil)
#define root_xiugai_bieming       NSLocalizedString(@"修改别名", nil)
#define root_xiugai_touxiang       NSLocalizedString(@"修改头像", nil)
#define root_xiugai_shebei      NSLocalizedString(@"删除设备", nil)

//设备二级
#define root_kongzhi      NSLocalizedString(@"控制", nil)
#define root_canshu      NSLocalizedString(@"参数", nil)
#define root_shuju      NSLocalizedString(@"数据", nil)
#define root_rizhi      NSLocalizedString(@"日志", nil)

//逆变器二级
#define root_ri_gonglv_zoushitu     NSLocalizedString(@"日功率走势图", nil)
#define root_NBQ_ri_dianliang      NSLocalizedString(@"日电量", nil)
#define root_dangqian_gonglv     NSLocalizedString(@"当前功率", nil)
#define root_NBQ_zong_dianliang      NSLocalizedString(@"总电量", nil)
#define root_NBQ_ri_fadianliang      NSLocalizedString(@"日发电量", nil)
#define root_NBQ_youxiao_gonglv     NSLocalizedString(@"设置有效功率", nil)
#define root_NBQ_wuxiao_gonglv      NSLocalizedString(@"设置无功功率", nil)
#define root_NBQ_PF      NSLocalizedString(@"设置PF值", nil)
#define root_NBQ_shijian     NSLocalizedString(@"设置逆变器时间:", nil)
#define root_NBQ_shifou_kaiqi      NSLocalizedString(@"是否确定开启逆变器", nil)
#define root_NBQ_shifou_guanbi     NSLocalizedString(@"是否确定关闭逆变器", nil)
#define root_NBQ_kaiguan     NSLocalizedString(@"设置逆变器开关机", nil)
#define root_NBQ_xunliehao     NSLocalizedString(@"序列号:", nil)
#define root_NBQ_leixing     NSLocalizedString(@"类型:", nil)
#define root_NBQ_shijianhao     NSLocalizedString(@"事件号:", nil)
#define root_NBQ_biaoshi     NSLocalizedString(@"标识:", nil)


//储能机二级
#define root_ri_fangdianliang      NSLocalizedString(@"日放电量", nil)
#define root_zong_fangdianliang     NSLocalizedString(@"总放电量", nil)
#define root_dianchi      NSLocalizedString(@"电池百分比(%)", nil)

#define root_CNJ_kaiguan      NSLocalizedString(@"设置储能机开关机", nil)
#define root_CNJ_SOC      NSLocalizedString(@"锂电池SOC下限设定", nil)
#define root_CNJ_shijian     NSLocalizedString(@"设置储能机时间", nil)
#define root_CNJ_fangdian_kaiguan      NSLocalizedString(@"强制放电使能", nil)
#define root_CNJ_fangdian_shijian       NSLocalizedString(@"强制放电时间段", nil)
#define root_CNJ_SP      NSLocalizedString(@"设置输入SP的组串电压", nil)
#define root_CNJ_kaiji      NSLocalizedString(@"开机", nil)
#define root_CNJ_guanji      NSLocalizedString(@"关机", nil)
#define root_CNJ_SOC_xia      NSLocalizedString(@"锂电池SOC下限设定", nil)
#define root_CNJ_shijian_she      NSLocalizedString(@"设置储能机时间:", nil)
#define root_CNJ_fangjian_shineng      NSLocalizedString(@"强制放电使能:", nil)
#define root_kai     NSLocalizedString(@"开", nil)
#define root_guan      NSLocalizedString(@"关", nil)
#define root_CNJ_fangdian_shijianduan     NSLocalizedString(@"强制放电时间段:", nil)
#define root_zhi      NSLocalizedString(@"至", nil)
#define root_CNJ_kailu_dianya      NSLocalizedString(@"开路电压(300~500V):", nil)
#define root_CNJ_MPP     NSLocalizedString(@"MPP电压:", nil)

#define root_CNJ_fuwuqi_cuowu    NSLocalizedString(@"所属服务器错误", nil)
#define root_CNJ_xuliehao_kong    NSLocalizedString(@"序列号为空", nil)
#define root_CNJ_buzaixian     NSLocalizedString(@"不在线", nil)
#define root_CNJ_caijiqi_buzai     NSLocalizedString(@"采集器不在线", nil)
#define root_CNJ_leixing_buzai     NSLocalizedString(@"参数类型不存在", nil)
#define root_CNJ_canshu_kong     NSLocalizedString(@"参数为空", nil)
#define root_CNJ_canshu_buzai_fanwei     NSLocalizedString(@"参数不在范围内", nil)
#define root_CNJ_shijian_budui     NSLocalizedString(@"时间参数不正确", nil)
#define root_CNJ_canshu_chenggong     NSLocalizedString(@"参数设置成功", nil)
#define root_CNJ_shifou_kaiqi_CNJ     NSLocalizedString(@"是否确定开启储能机", nil)
#define root_CNJ_shifou_guanbi_CNJ      NSLocalizedString(@"是否确定关闭储能机", nil)
#define root_Demo_tishi      NSLocalizedString(@"示范设备暂时不开放此功能,请安装真实产品使用此功能.", nil)


#define root_xinghao     NSLocalizedString(@"型号", nil)
#define root_xuleihao      NSLocalizedString(@"序列号", nil)
#define root_duankou     NSLocalizedString(@"端口", nil)
#define root_bieming      NSLocalizedString(@"别名", nil)
#define root_CNJ_eDing_gonglv      NSLocalizedString(@"额定功率", nil)
#define root_gujian_banben      NSLocalizedString(@"固件版本", nil)
#define root_shuxing      NSLocalizedString(@"属性", nil)
#define root_moshi     NSLocalizedString(@"模式", nil)

//数据采集器/编辑采集器
#define root_zubie     NSLocalizedString(@"组别", nil)
#define root_shebei_leixing    NSLocalizedString(@"设备类型", nil)
#define root_data_update_interval       NSLocalizedString(@"数据更新时间", nil)

#define root_tianjia_shebei      NSLocalizedString(@"添加设备", nil)
#define root_tianjia_chucuo      NSLocalizedString(@"添加出错", nil)
#define root_meiyou_quanxian      NSLocalizedString(@"没有权限", nil)
#define root_xuliehao_cuowu      NSLocalizedString(@"采集器序列号错误", nil)
#define root_zongti_shuliang_chaochu_xianzhi      NSLocalizedString(@"总体采集器数量超出限制", nil)
#define root_danGe_shuliang_chaochu_xianzhi      NSLocalizedString(@"单个电站采集器数量超出限制", nil)
#define root_xuliehao_yijing_cunzai      NSLocalizedString(@"采集器序列号已经存在", nil)
#define root_xuliehao_jiaoyanMa_bupipei      NSLocalizedString(@"序列号与校验码不匹配", nil)
#define root_shebei_tianjia_chenggong      NSLocalizedString(@"设备添加成功", nil)

#define root_CJQ_tianjia      NSLocalizedString(@"添加采集器", nil)
#define root_CJQ_bianji      NSLocalizedString(@"编辑采集器", nil)
#define root_CJQ_shanchu     NSLocalizedString(@"删除采集器", nil)
#define root_CJQ_peizhi      NSLocalizedString(@"配置采集器", nil)


#define root_Add       NSLocalizedString(@"Add", @"Add")
#define root_aliases       NSLocalizedString(@"aliases", @"aliases")
#define root_datalog_sn       NSLocalizedString(@"datalog sn", @"datalog sn")
#define root_group       NSLocalizedString(@"group", @"group")
#define root_device_type       NSLocalizedString(@"device type", @"device type")

#define root_Add       NSLocalizedString(@"Add", @"Add")
#define root_Modified       NSLocalizedString("Modified", @"Modified")
#define root_Delete       NSLocalizedString(@"Delete", @"Delete")
#define root_Aliases_can_not_be_empty       NSLocalizedString(@"Aliases can not be empty", @"Aliases can not be empty")
#define root_Successfully_modified       NSLocalizedString(@"Successfully modified", @"Successfully modified")
#define root_Modification_fails       NSLocalizedString(@"Modification fails", @"Modification fails")
#define root_Successfully_deleted       NSLocalizedString(@"Successfully deleted", @"Successfully deleted")
#define root_Delete_failed       NSLocalizedString(@"Delete failed", @"Delete failed")
#define root_Added_successfully       NSLocalizedString(@"Added successfully", @"Added successfully")

//添加数据采集器
#define root_Add       NSLocalizedString(@"Add", @"Add")
#define root_Enter_DatalogSN       NSLocalizedString(@"Enter DatalogSN", @"Enter DatalogSN")
#define root_Datalog_Valicode       NSLocalizedString(@"Datalog Valicode", @"Datalog Valicode")
#define root_Insert_true_datalog_sn       NSLocalizedString(@"Insert true datalog sn", @"Insert true datalog sn")
#define root_Datalog_verification_code_is_incorrect       NSLocalizedString(@"Datalog verification code is incorrect", @"Datalog verification code is incorrect")
#define root_Datalog_verification_code_is_incorrect       NSLocalizedString(@"Datalog verification code is incorrect", @"Datalog verification code is incorrect")
#define root_Added_Successfully       NSLocalizedString(@"Added Successfully", @"Added Successfully")
#define root_Add_Failed       NSLocalizedString(@"Add Failed", @"Add Failed")
#define root_Insert_datalog_code       NSLocalizedString(@"Insert datalog code", @"Insert datalog code")

//电站列表
#define root_Plant_List       NSLocalizedString(@"Plant List", @"Plant List")
#define root_Today_Energy       NSLocalizedString(@"Today Energy", @"Today Energy")
#define root_Total_Energy       NSLocalizedString(@"Total Energy", @"Total Energy")
#define root_Current_Power       NSLocalizedString(@"Current Power", @"Current Power")
#define root_Gains       NSLocalizedString(@"Gains", @"Gains")
#define root_Percentage       NSLocalizedString(@"Percentage", @"Percentage")
#define root_Storage_Status       NSLocalizedString(@"Storage Status", @"Storage Status")
#define root_Charge_Power       NSLocalizedString(@"Charge Power", @"Charge Power")
#define root_Discharge_Power       NSLocalizedString(@"Discharge Power", @"Discharge Power")
#define root_Add_Plant       NSLocalizedString(@"Add Plant", @"Add Plant")
#define root_Remove_Station       NSLocalizedString(@"Remove Station", @"Remove Station")
#define root_Upload_Picture       NSLocalizedString(@"Upload Picture", @"Upload Picture")
#define root_Setting_Station_Map       NSLocalizedString(@"Setting Station Map", @"Setting Station Map")
#define root_Installation_Information       NSLocalizedString(@"Installation Information", @"Installation Information")
#define root_plant_name       NSLocalizedString(@"plant name", @"plant name")
#define root_instal_date       NSLocalizedString(@"instal date", @"instal date")
#define root_company       NSLocalizedString(@"company", @"company")
#define root_power       NSLocalizedString(@"power", @"power")
#define root_Next       NSLocalizedString(@"Next", @"Next")

//电站详情
#define root_Plant_Detail       NSLocalizedString(@"Plant Detail", @"Plant Detail")
#define root_DAY       NSLocalizedString(@"DAY", @"DAY")
#define root_MONTH       NSLocalizedString(@"MONTH", @"MONTH")
#define root_YEAR       NSLocalizedString(@"YEAR", @"YEAR")
#define root_TOTAL       NSLocalizedString(@"TOTAL", @"TOTAL")
#define root_Daily_Returns       NSLocalizedString(@"Daily Returns", @"Daily Returns")
#define root_Daily_Electricity       NSLocalizedString(@"Daily Electricity", @"Daily Electricity")
#define root_Earnings       NSLocalizedString(@"Earnings", @"Earnings")
#define root_Month_energy       NSLocalizedString(@"Month energy", @"Month energy")
#define root_Earnings       NSLocalizedString(@"Earnings", @"Earnings")
#define root_Year_energy       NSLocalizedString(@"Year energy", @"Year energy")
#define root_Earnings       NSLocalizedString(@"Earnings", @"Earnings")
#define root_Total_energy       NSLocalizedString(@"Total energy", @"Total energy")
#define root_Powre       NSLocalizedString(@"Powre", @"Power")
#define root_Plant_Overview       NSLocalizedString(@"Plant Overview", @"Plant Overview")
#define root_Device_List       NSLocalizedString(@"Device List", @"Device List")
#define root_Event_List       NSLocalizedString(@"Event List", @"Event List")
#define root_Map       NSLocalizedString(@"Map", @"Map")
#define root_Voltage      NSLocalizedString(@"Voltage", @"Voltage")
#define root_Electron_flow      NSLocalizedString(@"Electron flow", @"Electron flow")

//详情（逆变器）
#define root_PV_POWER       NSLocalizedString(@"PV POWER", @"PV POWER")
#define root_PV1_VOLTAGE       NSLocalizedString(@"PV1 VOLTAGE", @"PV1 VOLTAGE")
#define root_PV1_ELEC_CURRENT       NSLocalizedString(@"PV1 ELEC-CURRENT", @"PV1 ELEC-CURRENT")
#define root_PV2_VOLTAGE       NSLocalizedString(@"PV2 VOLTAGE", @"PV2 VOLTAGE")
#define root_PV2_ELEC_CURRENT       NSLocalizedString(@"PV2 ELEC-CURRENT", @"PV2 ELEC-CURRENT")
#define root_R_PHASE_POWER       NSLocalizedString(@"R-PHASE POWER", @"R-PHASE POWER")
#define root_S_PHASE_POWER       NSLocalizedString(@"S-PHASE POWER", @"S-PHASE POWER")
#define root_T_PHASE_POWER       NSLocalizedString(@"T-PHASE POWER", @"T-PHASE POWER")
#define root_POWER       NSLocalizedString(@"POWER", @"POWER")
#define root_Energy       NSLocalizedString(@"Energy", @"Energy")

//详情（储能机）
#define root_CHARGING_POWER       NSLocalizedString(@"CHARGING POWER", @"CHARGING POWER")
#define root_DISCHARGING_POWER       NSLocalizedString(@"DISCHARGING POWER", @"DISCHARGING POWER")
#define root_INPUT_VOLTAGE       NSLocalizedString(@"INPUT VOLTAGE", @"INPUT VOLTAGE")
#define root_INPUT_CURRENT       NSLocalizedString(@"INPUT CURRENT", @"INPUT CURRENT")
#define root_USER_SIDE_POWER       NSLocalizedString(@"USER-SIDE POWER", @"USER-SIDE POWER")
#define root_GRID_SIDE_POWER       NSLocalizedString(@"GRID-SIDE POWER", @"GRID-SIDE POWER")

#define root_MONTH_BATTERY_CHARGE     NSLocalizedString(@"MONTH BATTERY CHARGE" , @"MONTH BATTERY CHARGE")
#define root_MONTHLY_CHARGED     NSLocalizedString(@"MONTHLY CHARGED", @"MONTHLY CHARGED")
#define root_MONTHLY_DISCHARGED     NSLocalizedString(@"MONTHLY DISCHARGED", @"MONTHLY DISCHARGED")
#define root_YEAR_BATTERY_CHARGE     NSLocalizedString(@"YEAR BATTERY CHARGE", @"YEAR BATTERY CHARGE")
#define root_YEAR_CHARGED     NSLocalizedString(@"YEAR CHARGED", @"YEAR CHARGED")
#define root_YEAR_DISCHARGED     NSLocalizedString(@"YEAR DISCHARGED", @"YEAR DISCHARGED")
#define root_TOTAL_BATTERY_CHARGE     NSLocalizedString(@"TOTAL BATTERY CHARGE", @"TOTAL BATTERY CHARGE")
#define root_TOTAL_CHARGED     NSLocalizedString(@"TOTAL CHARGED", @"TOTAL CHARGED")
#define root_TOTAL_DISCHARGED     NSLocalizedString(@"TOTAL DISCHARGED", @"TOTAL DISCHARGED")


#pragma mark - 能源

#define  root_energy_title        NSLocalizedString(@"能源", nil)
#define  root_energy        NSLocalizedString(@"能源分析", nil)
#define  root_energy_Smart       NSLocalizedString(@"智能能源", nil)
#define  root_energy_jiating_yongdian       NSLocalizedString(@"家庭用电量", nil)
#define  root_energy_jiating_shebei       NSLocalizedString(@"家庭用电设备", nil)
#define  root_energy_guangfu_dianliang      NSLocalizedString(@"光伏电量", nil)
#define  root_energy_chuneng_dianliang       NSLocalizedString(@"储能电量", nil)
#define  root_energy_chuneng_yue       NSLocalizedString(@"月:", nil)
#define  root_energy_chuneng_zuishengdian       NSLocalizedString(@"最省电:", nil)
#define  root_energy_chuneng_zuihaodian       NSLocalizedString(@"最耗电:", nil)
#define  root_energy_chuneng_ri       NSLocalizedString(@"日:", nil)

#define  root_energy_tiaodu_youxian      NSLocalizedString(@"能源调度优先级设置", nil)
#define  root_energy_liandong_shezhi       NSLocalizedString(@"智能联动设置", nil)
#define  root_energy_dianjia_shezhi       NSLocalizedString(@"峰谷电价设置", nil)
#define  root_energy_dongzuo_shineng       NSLocalizedString(@"峰谷段动作使能", nil)
#define  root_energy_kongzhi_youxian       NSLocalizedString(@"控制优先级设置", nil)
#define  root_energy_lingonglv_shineng       NSLocalizedString(@"光伏零功率输出使能", nil)
#define  root_energy_wenxin_tishi       NSLocalizedString(@"温馨提示", nil)
#define  root_energy_houxun_kaifang       NSLocalizedString(@"智能能源功能后续开放", nil)

#define  root_energy_jiating_yongdian_zhanbi       NSLocalizedString(@"家庭用电占比(Demo)", nil)
#define  root_energy_dianbinxiang       NSLocalizedString(@"电冰箱", nil)
#define  root_energy_weibolu       NSLocalizedString(@"微波炉", nil)
#define  root_energy_kongtiao       NSLocalizedString(@"空调", nil)
#define  root_energy_dianshiji       NSLocalizedString(@"电视机", nil)
#define  root_energy_xiyiji       NSLocalizedString(@"洗衣机", nil)
#define  root_energy_reshuiqi       NSLocalizedString(@"热水器", nil)
#define  root_energy_fadianliang       NSLocalizedString(@"发电量", nil)
#define  root_energy_fangdianliang       NSLocalizedString(@"放电量", nil)
#define  root_energy_zuidazhi       NSLocalizedString(@"最大值", nil)
#define  root_energy_pingjunzhi       NSLocalizedString(@"平均值", nil)

#pragma mark - 服务
#define  root_service        NSLocalizedString(@"服务", nil)
#define  root_ME_wenti       NSLocalizedString(@"我的问题", nil)
#define  root_ME_changjian_wenti        NSLocalizedString(@"常见问题", nil)
#define  root_ME_kefu        NSLocalizedString(@"客户服务", nil)
#define  root_ME_zhibao        NSLocalizedString(@"质保查询", nil)
#define  root_ME_zengzhi      NSLocalizedString(@"增值业务", nil)
#define  root_ME_gengduo       NSLocalizedString(@"更多产品", nil)

#define  root_ME_tijiao_wenti       NSLocalizedString(@"提交问题", nil)
#define  root_ME_biaoti       NSLocalizedString(@"标题:", nil)
#define  root_ME_wenti_leixing      NSLocalizedString(@"问题类型:", nil)
#define  root_ME_neirong      NSLocalizedString(@"内容:", nil)
#define  root_ME_biaoti_shuru      NSLocalizedString(@"请输入标题", nil)
#define  root_ME_wenti_leixing_xuanzhe      NSLocalizedString(@"请选择问题类型", nil)
#define  root_ME_xuliehao_shuru      NSLocalizedString(@"请输入序列号", nil)
#define  root_ME_fujian      NSLocalizedString(@"附件:", nil)
#define  root_ME_shangchuan_tupian      NSLocalizedString(@"请选择要上传图片", nil)
#define  root_ME_shuru_leirong      NSLocalizedString(@"请输入内容", nil)
#define  root_ME_tianjia_chenggong     NSLocalizedString(@"添加成功", nil)
#define  root_ME_tianjia_shibai      NSLocalizedString(@"添加错误", nil)

#define  root_ME_nibianqi_guzhan      NSLocalizedString(@"逆变器故障", nil)
#define  root_ME_chunengji_guzhan      NSLocalizedString(@"储能机故障", nil)
#define  root_ME_ruanjian_jianyi      NSLocalizedString(@"软件建议", nil)
#define  root_ME_ruanjian_guzhan      NSLocalizedString(@"软件故障", nil)
#define  root_ME_qita_shebei_guzhan      NSLocalizedString(@"其他设备故障", nil)
#define  root_ME_qita_wenti      NSLocalizedString(@"其他问题", nil)

#define  root_ME_wenti_liebiao      NSLocalizedString(@"问题列表", nil)
#define  root_ME_wei_chuli     NSLocalizedString(@"未处理", nil)
#define  root_ME_zhengzai_chuli      NSLocalizedString(@"正在处理", nil)
#define  root_ME_yi_chuli     NSLocalizedString(@"已处理", nil)
#define  root_ME_shanchu_liebiao    NSLocalizedString(@"删除列表", nil)
#define  root_ME_huifu_jilu    NSLocalizedString(@"回复记录", nil)
#define  root_ME_huifu   NSLocalizedString(@"回 复", nil)
#define  root_ME_chakan_tupian    NSLocalizedString(@"查看图片", nil)
#define  root_ME_gaisu    NSLocalizedString(@"概述", nil)
#define  root_ME_canshu    NSLocalizedString(@"参数", nil)
#define  root_ME_you  NSLocalizedString(@"有", nil)
#define  root_ME_meiyou    NSLocalizedString(@"没有", nil)
#define  root_ME_youwu_zhibao    NSLocalizedString(@"有无质保:", nil)
#define  root_ME_chuchang_shijian    NSLocalizedString(@"出厂时间:", nil)
#define  root_ME_daoqi_shijian    NSLocalizedString(@"到期时间:", nil)
#define root_zhibao_xunliehao     NSLocalizedString(@"序列号码:", nil)



#pragma mark - 我

#define   root_ME        NSLocalizedString(@"我", nil)
#define   root_WO_zhiliao_guanli        NSLocalizedString(@"资料管理", nil)
#define   root_WO_xitong_shezhi       NSLocalizedString(@"电站设置", nil)
#define   root_WO_xiaoxi_zhongxin      NSLocalizedString(@"消息中心", nil)
#define   root_WO_guanyu        NSLocalizedString(@"关于", nil)
#define   root_WO_xieyi        NSLocalizedString(@"用户协议", nil)
#define   root_WO_kefu_dianhua        NSLocalizedString(@"客服电话", nil)
#define   root_WO_jiancha_gengxin       NSLocalizedString(@"检查更新", nil)
#define   root_WO_zuixin_banben      NSLocalizedString(@"最新版本为", nil)
#define   root_WO_shifou_gengxin       NSLocalizedString(@"是否更新", nil)
#define   root_WO_shi_zuixin_banben       NSLocalizedString(@"您使用的是最新版本", nil)
#define   root_WO_zanbu       NSLocalizedString(@"暂不", nil)
#define   root_WO_liji_gengxin       NSLocalizedString(@"立即更新", nil)
#define   root_WO_pingguo_fuwuqi_shibai      NSLocalizedString(@"请求苹果服务器失败", nil)
#define   root_WO_xiugai_mima      NSLocalizedString(@"修改密码", nil)
#define   root_WO_xiugai_shoujihao      NSLocalizedString(@"修改手机号", nil)
#define   root_WO_xiugai_youxiang      NSLocalizedString(@"修改邮箱", nil)
#define   root_WO_xiugai_dailishang     NSLocalizedString(@"修改代理商编号", nil)
#define   root_WO_zhuxiao_zhanhao     NSLocalizedString(@"注销账号", nil)
#define   root_WO_shuru_shoujihao     NSLocalizedString(@"输入手机号", nil)
#define   root_WO_shuru_youxiang     NSLocalizedString(@"输入邮箱地址", nil)
#define   root_WO_shuru_dailishang    NSLocalizedString(@"输入代理商编号", nil)
#define   root_WO_yonghu_bucunzai     NSLocalizedString(@"用户不存在", nil)
#define   root_WO_anzhuang     NSLocalizedString(@"安装信息", nil)
#define   root_WO_dili     NSLocalizedString(@"地理信息", nil)
#define   root_WO_zijin     NSLocalizedString(@"资金收益", nil)
#define   root_WO_tupian    NSLocalizedString(@"电站图片", nil)
#define   root_WO_buneng_weikong    NSLocalizedString(@"不能为空", nil)
#define   root_WO_chengshi    NSLocalizedString(@"城市", nil)
#define   root_WO_shiqu    NSLocalizedString(@"时区", nil)
#define   root_WO_jingdu    NSLocalizedString(@"经度", nil)
#define   root_WO_weidu    NSLocalizedString(@"纬度", nil)
#define   root_WO_banbenhao    NSLocalizedString(@"当前版本:", nil)


#define   root_WO_dianji_huoqu    NSLocalizedString(@"点击获取", nil)
#define   root_WO_jieneng    NSLocalizedString(@"节约标准煤", nil)
#define   root_WO_C02    NSLocalizedString(@"CO2减排", nil)
#define   root_WO_SO2   NSLocalizedString(@"SO2减排", nil)

#define   root_FU_gaisu    NSLocalizedString(@"概述", nil)
#define   root_FU_fuwu_jieshao    NSLocalizedString(@"服务介绍", nil)
#define   root_FU_tigongshang    NSLocalizedString(@"提供商:", nil)
#define   root_FU_shiyong_quyu    NSLocalizedString(@"使用区域:", nil)
#define   root_FU_jiage    NSLocalizedString(@"价格:", nil)
#define   root_FU_lianxi_fangshi    NSLocalizedString(@"联系方式:", nil)

#define   root_shifou_shanchu_shebei    NSLocalizedString(@"是否确定删除设备", nil)

#define root_shanchu_chenggong      NSLocalizedString(@"删除成功", nil)
#define root_shanchu_shibai     NSLocalizedString(@"系统错误，删除失败", nil)

#define root_Ppv     NSLocalizedString(@"Ppv", nil)
#define root_Puser     NSLocalizedString(@"Puser", nil)
#define root_Pgrid     NSLocalizedString(@"Pgrid", nil)

#define root_Revenue     NSLocalizedString(@"Revenue", nil)
#define root_todayPV     NSLocalizedString(@"todayPV", nil)
#define root_PpvN     NSLocalizedString(@"PpvN", nil)

#define root_wo_qingkong_message     NSLocalizedString(@"清空", nil)

#define root_wo_qingkong_lishi_shuju     NSLocalizedString(@"是否清空历史数据", nil)
#define root_wenti_leirong    NSLocalizedString(@"问题内容:", nil)

//配置WIFI
#define root_peizhi_shinewifi    NSLocalizedString(@"配置ShineWifi", nil)
#define root_peizhi_shinewifi_yi    NSLocalizedString(@"ShineWifi提示一", nil)
#define root_peizhi_shinewifi_er    NSLocalizedString(@"ShineWifi提示二", nil)
#define root_peizhi_shinewifi_name    NSLocalizedString(@"ShineWifi输入路由器", nil)
#define root_peizhi_shinewifi_mima    NSLocalizedString(@"ShineWifi密码", nil)
#define root_peizhi_shinewifi_shuru_mima   NSLocalizedString(@"ShineWifi输入路由器密码", nil)
#define root_peizhi_shinewifi_xiugai_mima   NSLocalizedString(@"ShineWifi修改密码", nil)
#define root_peizhi_shinewifi_xin_mima   NSLocalizedString(@"ShineWifi新密码", nil)
#define root_peizhi_shinewifi_shuru_wifi_mima   NSLocalizedString(@"请输入Wifi密码", nil)
#define root_peizhi_shinewifi_shuru_chaxun_xinxi   NSLocalizedString(@"查询采集器信息", nil)
#define root_peizhi_shinewifi_xuliehao   NSLocalizedString(@"序列号", nil)
#define root_peizhi_shinewifi_jiaoyanma   NSLocalizedString(@"shinewifi校验码", nil)
#define root_peizhi_shinewifi_E  NSLocalizedString(@"配置ShineWifiE", nil)

#define root_peizhi_shinewifi_E_shaomiao   NSLocalizedString(@"扫描设备和设置路由器", nil)
#define root_peizhi_shinewifi_E_mingzi   NSLocalizedString(@"ShineWifiE名字", nil)
#define root_peizhi_shinewifi_peizhi_tishi   NSLocalizedString(@"配置提示", nil)


#define root_dianzhan_xuanzhe   NSLocalizedString(@"Choice", nil)
#define root_dianzhan_bianji   NSLocalizedString(@"编辑", nil)

#define root_chuneng_fangdianliang   NSLocalizedString(@"储能放电量", nil)

#define root_new   NSLocalizedString(@"新", nil)
#define root_tuijian  NSLocalizedString(@"推荐", nil)


#endif /* languageNew_h */
